### PR TITLE
fixed alphabetical order of country selector issue #329

### PR DESCRIPTION
**Pull request by S-mardii**

### CODE REVIEW

**Comment by acorbi** [comment]
@gimmemochi @DBishton @prustar @jpeizer1 Should we sort the country selector items alphabetically as proposed by @S-mardii or leave them as they are?

**Comment by Huyeng** [comment]
@acorbi, the country names should sort by alphabet, but ODMekong still keeps it as first menu item. 
I think it should be fine with this, right?
@S-mardii, please update the code to short only the country names not Mekong. Mekong should be first item as before. Sorry that I didn't provide the clear information to you.

**Comment by acorbi** [comment]
@Huyeng @S-mardii like it, merging

**Comment by gimmemochi** [comment]
Sorry, am late. Fully support the sorting of country by alphabetical order, with ODM keeping the first position.

**Pull request merged**
