### PR TITLE
Fixes #172

### LINKED ISSUE #172: Dataset detail page Admin Function
When a detailed data page has been loaded on WP it would be handy to have an ADMIN function (hidden from the users) to be able to directly go to the resource in CKAN to make edits if necessary.

### PR DESCRIPTION
**Pull request by acorbi**
Adds a button that takes to the CKAN edit screen

screenshot from 2017-01-30 14-49-42

### CODE REVIEW

**Comment by acorbi** [comment]
@Huyeng please review this when you have the chance

**Comment by Huyeng** [comment]
@alex, I should show the hyperlink (Edit or Manage) next to the title. It can be seen when login only because CKAN it the back end now.  
screenshot at jan 30 21-06-56

**Comment by acorbi** [comment]
@Huyeng the "Manage on CKAN" button also ONLY appears when user is logged-in on WORDPRESS. It won't appear for normal users. In regards to the style of the edit button I would leave it on the sidebar because this function is only for internal use and as long as it offers the wished functionality and does not disturb editors' work should be fine

**Comment by Huyeng** [comment]
Well, I just would like to reduce some space. Anyways, If it is the internal, it is ok.

**Comment by acorbi** [comment]
ok, then let's merge it! thanks for your feedback

**Pull request merged**
