### PR TITLE
[IMP] Remove min max validation date range

### PR DESCRIPTION
**Pull request by S-mardii**
Fixed issue based on comment on pull request #1333

### CODE REVIEW

**Comment by EricSoroos** [comment]
This is on PP now.

**Comment by S-mardii** [comment]
PP is still down

**Comment by EricSoroos** [comment]
Ok, PP is back.

**Comment by S-mardii** [comment]
@EricSoroos This feature is now working fine on PP. Please push to Prod

**Comment by EricSoroos** [comment]
This is on prod now.

**Pull request merged**
