### PR TITLE
[IMP] Enhance post-list-single-1-cols widget layout

### PR DESCRIPTION
**Pull request by S-mardii**
- Remove some classes that add unnecessary padding to the widget
- Refactor codes

### CODE REVIEW

**Comment by EricSoroos** [comment]
Ok, This is on PP

**Comment by S-mardii** [comment]
@EricSoroos Tested and it looks fine on PP. Please pull to Prod

**Comment by S-mardii** [comment]
@EricSoroos I just wanna make a quick follow up whether this code has been pulled to Prod.

**Comment by EricSoroos** [comment]
No. It doesn't look like it.

We've still got the max-datepicker issue that's in master, so that feature would be broken if this were pulled. I don't know if that would prevent you from editing pages if it got merged in. 

I think to fix it we would need to remove the validation that was modified in #1333.

**Comment by S-mardii** [comment]
Hello @EricSoroos is this pulled to Prod?

**Comment by EricSoroos** [comment]
Yep, from prod:
```
commit fb0a4f7792dcc5ac6ef1a202e8d96936cc95d262
Merge: 454d52c 97e8d72
Author: Eric Soroos <36156267+EricSoroos@users.noreply.github.com>
Date:   Fri Apr 22 11:39:36 2022 +0100

    Merge pull request #1335 from OpenDevelopmentMekong/impl-1334
    
    [IMP] Enhance post-list-single-1-cols widget layout

```

**Pull request merged**
