### PR TITLE
Myanmar font embed

### PR DESCRIPTION
**Pull request by DragonVirus**
Font embedded for Myanmar site. Implement the same way as Cambodia site. 

Need to install https://www.npmjs.com/package/request for font import
`npm install -g request`

### CODE REVIEW

**Comment by acorbi** [comment]
> Need to install https://www.npmjs.com/package/request for font import
> npm install -g request

please @DragonVirus add it as dependency on pacakge.json

**Comment by acorbi** [comment]
@DragonVirus thanks for adding the dependency.

Before we merge this PR, can you please elaborate a bit more on which elements would be tagged with ```class="my"``` for the new font to be applied? Can you present some quick examples?

**Comment by DragonVirus** [comment]
@acorbi the class is already on html tag when the language is changed. (Added by q-Translate-X ?)
Cambodia site is applied the same with .km class.

**Comment by acorbi** [comment]
@DragonVirus oh I see. Yeah, that should be q-translateX .

merging!

**Pull request merged**
