### PR TITLE
Fixes #1125

### LINKED ISSUE #1125: Code a reusable dialog for mobile menus
Using HTML + CSS + JS, code a mechanism which can be re-used across the system to create utility dialogs which:

- Are tagged with a particular class **mobile-dialog**
- Do not change if the user is on desktop
- Are initially hidden
- Are shown (via slide-in or fade-in effects) after a button is tapped. This button will get a particular class **open-mobile-dialog**
- Are hidden again (via slide-out or fade-out effects) after a button is tapped. This button will get a particular class **close-mobile-dialog**

### PR DESCRIPTION
**Pull request by acorbi**
# WIP: Please do not merge yet

@Huyeng please test this branch on both your desktop and mobile and give me your opinion. basically I have implemented a class `.mobile-dialog` that, when assigned to a `<div>` cases it to be hidden by default and shown when the user clicks on an element assigned with the class `.open-mobile-dialog`. In the case of this PR the category selection box `.category-map-layers` gets the `.mobile-dialog` class and the newly-added layers control the `.open-mobile-dialog` in order to open it.

## Changelog

Refactored leaflet controls (added jeo.layers) and mapping functions:
- get_all_layers_legend
- get_all_layers

Added .mobile-dialog class and js logic

### CODE REVIEW

**Comment by Huyeng** [comment]
Got error: 
Fatal error: Class 'Mobile_Detect' not found in \inc\screen-manager.php on line 17

**Comment by Huyeng** [comment]
I fixed it now by run the composer install/update.  Anyways, I would to suggest to notify if the computer is not installed or Mobile_Detect class is not found.

**Comment by Huyeng** [comment]
Even, the composer is installed, the class is still not found. It was solved by adding the "__DIR__". 
I don't think will cause any error on your part. 

Suggestion, if it looks fine for you, please add "__DIR__" every time you require  '/vendor/autoload.php';

**Comment by acorbi** [comment]
@Huyeng @DragonVirus Closing this PR, instead of merging to master we should be merging all 2.4.0-related into **impl-2.4.0** branch

**Pull request closed without merging**
