### PR TITLE
Impl 716

### PR DESCRIPTION
**Pull request by Huyeng**
Fixes # Impl 716
Adding Filter box

### CODE REVIEW

**Comment by acorbi** [comment]
@Huyeng I have tested this implementation on PP and there are still a number of bugs that need to be fixed before merging:

## Topic value is not selected in the topic box after filtering by topic

Steps to reproduce the issue:

1. Go to an archive page such as https://pp.opendevelopmentmekong.net/news
2. Filter by any topic (example Land)
3. Click **Search filter** button

**Expected behaviour**
When the result page loads, the topic **Land** should be selected on the Topic dropdown box.

**Observed behaviour**
The topic dropdown box is empty

## Javascript error on profile archive page

Steps to reproduce the issue:

1. Go to https://pp.opendevelopmentcambodia.net/profiles
2. Enter any search term on the **Text search** field (example: land)

**Expected behaviour**
When the result page loads, only profiles related to land should be listed

**Observed result**
screenshot from 2017-02-01 09-36-50

**Comment by Huyeng** [comment]
@acorbi - The error caused by https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/732.  The task has been working while it is waiting for merging this PR. the https://github.com/OpenDevelopmentMekong/wp-odm_theme/pull/733
It means that when the branch was created before the issue fixed/merged.

**Comment by Huyeng** [comment]
Please merge with master, and test again.

**Comment by acorbi** [comment]
@Huyeng another issue, please take a look:

## Profile not being found after specifying text and topic filter

Steps to reproduce the Issue:

1. Go to https://pp.opendevelopmentcambodia.net/profiles
2. Enter Health on **text search** and ** Government services** in topic filter
3. Click **Search filter** button

**Expected behaviour**
I expect the **health services and centers** profile to appear on the list: https://pp.opendevelopmentcambodia.net/profiles/access-to-public-service/health-services-and-centers/

**Observed behaviour**
I am taken to the 404 page, no results.

**Comment by Huyeng** [comment]
I followed you step, I got the result as expected:
Health services and centers  and Civil status 

Civil status contains some words of health, that's why it also appear because WP not only search on Title but also the content as well.

Result url: https://pp.opendevelopmentcambodia.net/profiles?odm_advanced_nav=1&filter_=1&filter_post_type%5B%5D=profiles&filter_s=Health&filter_category%5B%5D=30944&filter_date_start=&filter_date_end=

screenshot at feb 01 21-48-51

**Pull request merged**
