### PR TITLE
Fixes #598

### LINKED ISSUE #598: Create disclaimer popup to be displayed on ODT and ODL
Hi @acorbi ,

Please create a disclaimer popup for OD Laos and OD Thailand that contains the following text:

"Open Development Initiative supports a network of organizations co-managing a common open data and knowledge platform to illuminate development trends in the Lower Mekong region at country and regional levels. Would you like to join efforts with us in building a data and information ecosystem to support transparent sharing of development data and inform constructive dialogue and decision making for sustainable development in Laos? We are looking for national partners to contribute to establishing Open Development Laos. Learn about how you may participate here. "

The disclaimer should also appear on the Land topic page with a slightly different text:

"Open Development Initiative is currently seeking partners to manage Open Development Laos. This page is published here to demonstrate a redesigned user interface with improved navigation and content discoverability. The country site selector on the top bar allows users to discover similar content on another country site or the regional site. Click on the  Open Development Mekong logo on the country selector bar to read about land governance at the regional level or click on the  Open Development Cambodia logo to read about land governance in Cambodia. Would you like to contribute to Open Development Laos? Please get in touch with us. "

### PR DESCRIPTION
**Pull request by acorbi**
Fixes #598

### CODE REVIEW

**Comment by acorbi** [comment]
@DBishton @Huyeng I did the adjustments we discussed on our last meeting about the notification. 

As discussed, the notification stays on the header of the site and can be dismissed by clicking the (X). The notification is also shown in the map explorer which takes the full height of the screen again when the notification is dismissed.

Please see the screenshots below and provide feedback on whether we should consider this final:

screenshot from 2016-12-12 14-16-44

screenshot from 2016-12-12 14-17-20

screenshot from 2016-12-12 14-16-58

screenshot from 2016-12-12 14-17-35

**Comment by Huyeng** [comment]
@acorbi, the team still prefers the solid color (green) of the border as current existing on the website. 
The close button looks fine to us.

**Comment by acorbi** [comment]
@huyeng got it, will change the color and re-submit screenshots

**Comment by acorbi** [comment]
@Huyeng @dbishton Updated the colour. See screenshots below. Is good to go live?

screenshot from 2016-12-13 08-57-50
screenshot from 2016-12-13 09-00-00

**Comment by Huyeng** [comment]
Thanks @acorbi.

**Comment by gimmemochi** [comment]
Looks good to me @acorbi Thank you.

**Pull request merged**
