### PR TITLE
Fixs title link errors and reduce size of thumbnail

### LINKED ISSUE #360: The links of the layer items on Map catalogue not working properly
On the map catalogue is the place where users can download different kind of map data.
It is assumed that all the layers on map catalogue have resource stored on ckan, so when we click on the any title of layer, it should point to the data page.

For example: 
Aqueduct Atlas – Available Blue Water :  https://cambodia.opendevelopmentmekong.net/dataset/?id=cambodian-aqueduct-atlas

However, click on Access to Public Transport, it pointed to the page that contain only the image: 
https://cambodia.opendevelopmentmekong.net/layers/bus-lines/
Actually, it should point to https://cambodia.opendevelopmentmekong.net/dataset/?id=public-transportation

### PR DESCRIPTION
**Pull request by Huyeng**
Fixes #360

### CODE REVIEW

**Comment by acorbi** [comment]
@Huyeng im reviewing it now. Does this PR Fixes any issue? If so, please add **Fixes #XXX" on the title or description of the PR so the issue gets automatically closed.

**Comment by Huyeng** [comment]
Yes, please merge it.

**Comment by acorbi** [comment]
Potentially fixes #348 as well

**Comment by acorbi** [comment]
@huyeng we need to specufy the thumbnail size in all the templates (both grid and list layout). can you please do the change? im still afk...

**Pull request merged**
